### PR TITLE
Run standard for all files.

### PR DESCRIPTION
**Pull request by XhmikosR**
@Johann-S feel free to tweak this so that it passes. Not sure why those global vars in docs/js/main.js.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Yeah, but it doesn't seem you use the variables at all.

**Comment by Johann-S** [comment]
The variables are used in the HTML see: https://github.com/Johann-S/bs-stepper/blob/58eb2291f5c34fd8435ae0adf5480e01f35a8656/docs/index.html#L70

**Comment by XhmikosR** [comment]
Perfect. So maybe doing window.var is better since we explicitly assign it
globally

**Comment by Johann-S** [comment]
Hmm you're right it should fix that 👍

**Pull request merged**
