### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
- [x] Needs `BROWSER_STACK_ACCESS_KEY` and `BROWSER_STACK_USERNAME` added in the repo secrets
- [x] Branch protection rules need to be adapted
- [x] Remove Travis CI from repo **integrations/apps/hooks**
- [ ] I've yet to find a way to skip the BrowserStack tests like before with `[skip browser]`

### CODE REVIEW

**Comment by Johann-S** [comment]
@XhmikosR I added BROWSER_STACK_ACCESS_KEY and BROWSER_STACK_USERNAME in repo secrets

**Comment by XhmikosR** [comment]
@Johann-S seems to be good now :)

If you take care of the rest of the TODO (minus the skip test), we can merge this.

**Comment by XhmikosR** [comment]
Oh, and I'd remove the secrets from the Travis project before removing it.

**Comment by Johann-S** [comment]
I took care of the rest of the todo 😉

**Pull request merged**
