### PR TITLE
feat(events): dispatch show events (show and shown)

### PR DESCRIPTION
**Pull request by Johann-S**
Add `show.bs-stepper` and `shown.bs-stepper` events

Things to do:
- [x] Add show and shown events
- [x] Update the docs
- [x] Fix unit tests

/CC @kstratis

Fixes: #21

### CODE REVIEW

**Comment by Johann-S** [comment]
@kstratis I'll wait a bit before merging that so do not hesitate if you have any feedbacks 👍

You can download the built file here: https://deploy-preview-27--bs-stepper.netlify.com/dist/js/bs-stepper.min.js

**Comment by kstratis** [comment]
@Johann-S Great job! Thanks for adding support!

**Comment by Johann-S** [comment]
you're welcome 👍 
I'll push a new release soon 👍

**Comment by Johann-S** [comment]
@kstratis published 😉

**Pull request merged**
